Repository leonsteinhaeuser/project-beta-automations, pull requests merged in 2022-01, with the labels that each got.

#23 feature: custom fields support
  README.md
  action.yml
  entrypoint.sh
  entrypoint_user.sh
  gh_api_global.sh
  gh_api_lib_organization.sh
  gh_api_lib_user.sh
  test_organization.sh
  test_user.sh
Labels: size/M, new feature

#24 docs: added minor improvements
  README.md
Labels: documentation, enhancement, size/XS

#26 Update readme to point to valid release tag
  README.md
Labels: documentation, enhancement

#28 fix: status value not required
  entrypoint.sh
  test_user.sh
Labels: bug fix, size/XS
